[build]
builder = "NIXPACKS"
buildCommand = "python -m ensurepip && python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 